apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2
  labels:
    purpose: ingress
    project: roboshop
    app: app-2
spec:
  replicas: 2
  selector:
    matchLabels:
      purpose: ingress
      project: roboshop
      app: app-2
  template:
    metadata:
      labels:
        purpose: ingress
        project: roboshop
        app: app-2
    spec:
      containers:
      - name: app-2
        image: gsurendhar/app2:v1
---
apiVersion: v1
kind: Service
metadata:
  name: app-2
  labels:
    purpose: ingress
    project: roboshop
    app: app-2
spec:
  selector:
    purpose: ingress
    project: roboshop
    app: app-2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: app-2
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:293282637741:certificate/f440a85f-ccd6-4394-91af-4cc77762962a # your ACM Certificate ARN need to add
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: joindevops
spec:
  ingressClassName: alb
  rules:
  - host: "app1.gonela.site"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app1
            port:
              number: 80      # app-2 service port